### ISSUE TITLE
I have question about getting baseaddress for other devices

### ISSUE THREAD

**Issue by Gezine** [map220v/edk2-a72q#2]
In the file GalaxyA72.fdf

BaseAddress   = 0x9FC00000|gArmTokenSpaceGuid.PcdFdBaseAddress  # The base address of the Firmware in NOR Flash.
Size          = 0x00200000|gArmTokenSpaceGuid.PcdFdSize         # The size in bytes of the FLASH Device

How do I calculate this value for other devices?
I'm trying to port edk2 for SD778G devices.
Any help would be appreciated

**Comment by map220v** [comment]
This address i got from [uefiplat.cfg](https://github.com/map220v/samsung-a72q-efi_drivers/blob/d5375c24e5df78ab8c0026a179e4d4b5af72f171/xbl/Other/uefiplat.cfg#L19) in xbl.efi

**Comment by Gezine** [comment]
Thank you for your reply
Are there any other device specific values that I should care?
How do I make ACPI tables?

**Comment by map220v** [comment]
Addresses in [DeviceMemoryMap.h](https://github.com/map220v/edk2-a72q/blob/main/GalaxyA72/Include/Configuration/DeviceMemoryMap.h) needs to be changed to make dxe's work.(uefiplat.cfg has all needed addresses)

ACPI tables in this repo, from sc7180(it's exactly same SOC as sm7125 but with stronger cores)
sm7325 most likely same as sc7280 because they share same codename "yupik"

**Comment by Gezine** [comment]
So to get ACPI tables I need to extract it from SC7280 devices?

**Comment by Gezine** [comment]
I changed every addresses in DeviceMemoryMap.h using my uefiplat.cfg except this

#ifdef MEMORY_8G
    {0xC0000000, 0x1C0000000, EFI_RESOURCE_SYSTEM_MEMORY,
     SYSTEM_MEMORY_RESOURCE_ATTR_CAPABILITIES, ARM_MEMORY_REGION_ATTRIBUTE_WRITE_BACK,
     AddMem, EfiConventionalMemory},
    #else
    {0xC0000000, 0x140000000, EFI_RESOURCE_SYSTEM_MEMORY,
     SYSTEM_MEMORY_RESOURCE_ATTR_CAPABILITIES, ARM_MEMORY_REGION_ATTRIBUTE_WRITE_BACK,
     AddMem, EfiConventionalMemory},
    #endif

Where did you find 0xC0000000 address?
I couldn't find this in uefiplat.cfg

**Comment by map220v** [comment]
It's from /proc/last_kmsg(xbl boot part)
![mem](https://user-images.githubusercontent.com/14368485/159213712-e677dcb0-b746-4e00-a8a3-bd639bc3711b.png)
I Combined Size of RAM Entry 1 and RAM Entry 2 to get 0x1C0000000
And used RAM Entry 2 Base as starting Address

I didn't used RAM Entry 0 because it's used by some things like "HYP" or "SMEM"

Edit: also you need to change [GalaxyA72_6G.dsc](https://github.com/map220v/edk2-a72q/blob/1c67b1bc9c6bff4756dd7da9c817f34c1756aff2/GalaxyA72/GalaxyA72_6G.dsc#L16)
In 8G version i combined RAM Entry 1 Base and Size to get 0x280000000 and subtracted by 0x80000000 to get full memory size after 0x80000000

**Comment by Gezine** [comment]
UEFI Start     [ 1196]
 - 0x09FC01000 [ 1198] Sec.efi
ASLR        : ON
DEP         : ON (RTB)
Timer Delta : +1 mS
RAM Entry 0 : Base 0x0080000000  Size 0x003A800000
RAM Entry 1 : Base 0x0100000000  Size 0x0100000000
RAM Entry 2 : Base 0x00C0000000  Size 0x0040000000

Didn't know samsung devices had /proc/last_kmsg support

So I think I changed everything but my device (Galaxy Tab S7 FE Wifi 6G RAM) keep stuck at boot screen

![20220321_170231](https://user-images.githubusercontent.com/30000519/159223357-54bb20ee-cd27-4669-81b6-0d86486849a6.jpg)

What is expected behaviour when edk2 boot up?
Does it show efi shell screen?

My device have vendor_boot.img and boot.img (both using android boot image version 3)
Can this be a problem?

**Comment by map220v** [comment]
In [GalaxyA72.dsc](https://github.com/map220v/edk2-a72q/blob/1c67b1bc9c6bff4756dd7da9c817f34c1756aff2/GalaxyA72/GalaxyA72.dsc#L130) Change Address to "Display Reserved" from uefiplat.cfg to make Framebuffer work.

It's seems edk2 boots.
If there is problem with boot.img it's should fail booting zImage and go to OdinApp.

**Comment by Gezine** [comment]
That was it!
Changin framebuffer address did the trick

![20220321_172310](https://user-images.githubusercontent.com/30000519/159226101-8ae18b90-fea8-4ac1-903c-3adeb68af6c9.jpg)

But it crashes with Synchronous Exception at 0x00000001FF2954D0
Have any clue about it?

**Comment by Gezine** [comment]
![20220321_174508](https://user-images.githubusercontent.com/30000519/159228701-376a0ac9-f686-490c-a754-5e4c03445591.jpg)

Recompiled DEBUG build for more logs

**Comment by map220v** [comment]
Try to remove [this line](https://github.com/map220v/edk2-a72q/blob/1c67b1bc9c6bff4756dd7da9c817f34c1756aff2/GalaxyA72/GalaxyA72.dsc#L95) (without this line it's should get correct timer frequency)
Edit: it's seems this value is the same in sm7325

**Comment by map220v** [comment]
Maybe [PcdArmArchTimer*](https://github.com/map220v/edk2-a72q/blob/1c67b1bc9c6bff4756dd7da9c817f34c1756aff2/GalaxyA72/GalaxyA72.dsc#L106-L109) is different on sm7325.
I never had this error before.

**Comment by Gezine** [comment]
Tried removing multiple lines but no go
Any other suggestions?

Oh BTW I commented out all ACPI related lines
Can this be a problem?

**Comment by map220v** [comment]
Correct [PcdArmArchTimer*](https://github.com/map220v/edk2-a72q/blob/1c67b1bc9c6bff4756dd7da9c817f34c1756aff2/GalaxyA72/GalaxyA72.dsc#L106-L109) is required for TimerDxe to work.

ACPI tables only used in windows.

**Comment by Gezine** [comment]
[deleted]

ABL and XBL files

[deleted]

edk2 now I am using

Can this will help you?

**Comment by map220v** [comment]
Try this values:
gArmTokenSpaceGuid.PcdArmArchTimerSecIntrNum|29
gArmTokenSpaceGuid.PcdArmArchTimerIntrNum|30
gArmTokenSpaceGuid.PcdArmArchTimerHypIntrNum|0 #or 26 
gArmTokenSpaceGuid.PcdArmArchTimerVirtIntrNum|27

**Comment by Gezine** [comment]
Sadly still no go for both values (0 or 26)

**Comment by map220v** [comment]
Try commenting TimerDxe.inf in SMT733.dsc and SMT733.fdf and use TimerDxe.efi from xbl
  FILE DRIVER = 49EA041E-6752-42CA-B0B1-7344FE2546B7 {
    SECTION DXE_DEPEX = SMT733/Binary/ArmTimerDxe/ArmTimerDxe.depex
    SECTION PE32 = SMT733/Binary/ArmTimerDxe/ArmTimerDxe.efi
    SECTION UI = "ArmTimerDxe"
  }
[ArmTimerDxe.zip](https://github.com/map220v/edk2-a72q/files/8314780/ArmTimerDxe.zip)

**Comment by Gezine** [comment]
I think it worked!

![20220321_200057](https://user-images.githubusercontent.com/30000519/159248283-3ece7c24-187f-48d0-b671-2b9c21f61a8f.jpg)

But I think UFS driver from 845 causes crash
Which tool did you use to extract efi drivers from XBL?
I might try put every efi drivers on to it

**Comment by map220v** [comment]
Yes UFSDxe from 845 uses qcom ufs protocol v3 and sm7325 most likely has v4 or v5.

I used UEFITool.exe to extract it.

**Comment by Gezine** [comment]
How do I get GUID thing like this?
FILE DRIVER = 49EA041E-6752-42CA-B0B1-7344FE2546B7
Does UEFITool provide it?

**Comment by map220v** [comment]
Yes. UFSDxe has same GUID in sm7325 "0D35CD8E-97EA-4F9A-96AF-0F0D89F76567"
[UFSDxe.zip](https://github.com/map220v/edk2-a72q/files/8314983/UFSDxe.zip)

**Comment by Gezine** [comment]
https://user-images.githubusercontent.com/30000519/159259476-62c5f670-6bf9-4c64-a1a3-86c4d9d588f0.mp4

I think there is no error but device just automatically reboots after several times
I checked log frame by frame but there was no errors
What would be the problem?

**Comment by map220v** [comment]
UFSDxe and other drivers in xbl uses it's own DebugLib, etc. Thats why it's doesn't print errors.
It's seems UFSDxe gives Assert (in qcom edk2 prod build, assert writes to pshold address to reboot phone)

Also making UFS work on samsung can be really hard.
![ufssamsung](https://user-images.githubusercontent.com/14368485/159260785-09393850-a300-4bb7-916a-11eefc7eb422.png)

**Comment by Gezine** [comment]
Damn if I cannot use UFS
Is there a chance that I can use SDcard instead?
My galaxy tab have SDcard slot

**Comment by Gezine** [comment]
![20220321_213344](https://user-images.githubusercontent.com/30000519/159261882-09c1f0a4-83d8-477c-adb2-7ff4adfe4360.jpg)

BTW disabling UFS driver did loaded efi shell
How do I type anything in efi shell?
Does usb OTG works?

**Comment by map220v** [comment]
Making SDCard work even harder, it's requires SdccDxe.efi patch(to enable driver loading, It's disabled by default because UFS boot mode is default) and PMIC.efi

OTG doesn't work without PMIC.efi

And we don't have PMIC.
![samsung](https://user-images.githubusercontent.com/14368485/159262531-e188dfd7-2342-41be-8fc7-29b50063637a.png)

**Comment by Gezine** [comment]
Damn am I doomed then?
No UFS, SDcard, USB
What would be other alternatives?

**Comment by map220v** [comment]
Right now windows impossible to make work on samsung because storufs.sys causes some weird issues with Samsung UFS. (WinPE only if UFSDxe somehow works)

The only things that has working UFS is downstream linux kernel and mainline linux kernel.

**Comment by Gezine** [comment]
Thank you for teaching me whole day for me.
Have a nice day
